from __future__ import annotations

from collections.abc import Iterator
from typing import Any

class ArtifactoryException(Exception): ...

class ArtifactoryPath:
    repo: str
    path_in_repo: str
    name: str
    parent: ArtifactoryPath

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def stat(self) -> Any: ...
    def glob(self, pattern: str) -> Iterator[ArtifactoryPath]: ...
    def iterdir(self) -> Iterator[ArtifactoryPath]: ...
    def read_text(self, encoding: str = ...) -> str: ...
    def write_text(self, content: str, encoding: str = ...) -> int: ...
    def download_stats(self) -> Any: ...
    @property
    def properties(self) -> dict[str, Any]: ...
    def __getattr__(self, name: str) -> Any: ...

class ArtifactorySaaSPath(ArtifactoryPath): ...
